import{_ as e,o,c as a,a as t}from"./app-BihAYnmf.js";const c={},n=t("p",null,"throws、 throw、 try、 catch、 finally",-1),s=t("p",null,"try⽤来指定⼀块预防所有异常的程序；",-1),l=t("p",null,"catch⼦句紧跟在try块后⾯， ⽤来指定你想要捕获的异常的类型；",-1),r=t("p",null,"finally为确保⼀段代码不管发⽣什么异常状况都要被执⾏；",-1),i=t("p",null,"throw语句⽤来明确地抛出⼀个异常；",-1),_=t("p",null,"throws⽤来声明⼀个⽅法可能抛出的各种异常；",-1),d=[n,s,l,r,i,_];function h(p,m){return o(),a("div",null,d)}const f=e(c,[["render",h],["__file","keyword-about-exception.html.vue"]]),w=JSON.parse('{"path":"/docs/java/java-basic/keyword-about-exception.html","title":"","lang":"en-US","frontmatter":{},"headers":[],"git":{"createdTime":1715384499000,"updatedTime":1715384499000,"contributors":[{"name":"dong","email":"dwx_job@163.com","commits":1}]},"filePathRelative":"docs/java/java-basic/keyword-about-exception.md"}');export{f as comp,w as data};
